services:
  php:
    build: docker/php
    command: "-S 0.0.0.0:8080 -t public"
    depends_on:
      - db
    environment:
      DOCKER: "true"
    networks:
      - bridge
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
      - ./logs:/var/www/logs
    working_dir: /var/www
  db:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD='true'
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_HOST
    image: mysql
    networks:
      - bridge
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
networks:
  bridge: {}
version: '3'
volumes:
  data: {}
